version: '3.8'
services:
  web:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm
    hostname: php-fpm
    volumes:
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
      - ./app:/app

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    hostname: mariadb
    volumes:
      - ./app:/app
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
